# Generated by Django 3.1.7 on 2021-03-09 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
